DateFormat = '2006-01-02'

# defaultTheme = 'auto'
# defaultTheme = 'light'
defaultTheme = 'dark'

ShowWordCount = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowCodeCopyButtons = true
ShowAllPagesInArchive = true

cdnPrefix = "https://img.ioo.pw"

[author]
    name = "NACGNOH"

[webpCloudProxy]
    enabled = true
    proxyUrl = "https://047a117.webp.li"
    convertTypeList = ["jpg", "jpeg", "png", "gif"]

[profileMode]
    enabled = true

    title = "NACGNOH"
    subtitle = '『Just so so...』'
    imageUrl = 'https://avatars.githubusercontent.com/u/46992517?v=4'

    [[profileMode.buttons]]
        name = '🈲'
        url = 'hobby'

    [[socialIcons]]
        name = 'github'
        url = 'https://github.com/ilunp/'

    [[socialIcons]]
        name = 'email'
        url = 'mailto:ilunp@qq.com'

    [[socialIcons]]
        name = 'rss'
        url = 'index.xml'