name: GitHub Pages Deploy

on:
  push:
    branches:
      - main  # Set a branch to deploy
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Get Games Data
        env:
          STEAM_KEY: ${{ secrets.STEAM_KEY }}
          STEAM_ID: ${{ secrets.STEAM_ID }}
        run: |
          mkdir -p data
          curl -s "https://api.steampowered.com/IPlayerService/GetOwnedGames/v1/?key=${STEAM_KEY}&steamid=${STEAM_ID}&format=json&include_appinfo=true&include_played_free_games=true" \
          | jq '.response | {game_count: [.games[] | select(.playtime_forever > 600)] | length, games: [.games[] | select(.playtime_forever > 600)] | sort_by(-.playtime_forever)}' \
          > data/game.json

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: ilunp.com